### ISSUE TITLE
`stdout: EOF` panic from bridge update

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-aiven#110]
It looks like the bridge update in [3.4.0](https://github.com/pulumi/pulumi-aiven/blob/master/CHANGELOG.md#340-2021-01-29) has caused a panic when using this provider.

## Current behavior

The code below will panic for any `@pulumi/aiven` version 3.4.0 and greater.

#### Panic
  
```
% pulumi pre                           
Previewing update (dev)

View Live: https://app.pulumi.com/clstokes/aiven-stdout-eof/dev/previews/97cf9572-fce7-4964-8a0d-075b5ebe6370

     Type                       Name                  Plan       Info
 +   pulumi:pulumi:Stack        aiven-stdout-eof-dev  create     8 messages     └─ pulumi:providers:aiven  main                             1 error
 
Diagnostics:
  pulumi:pulumi:Stack (aiven-stdout-eof-dev):
    panic: strconv.ParseUint: parsing "": invalid syntax
    goroutine 1 [running]:
    github.com/pulumi/pulumi-terraform-bridge/v2/pkg/tfbridge.GetModuleMajorVersion(0x0, 0x0, 0xc00055daf0, 0x1)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v2@v2.19.0/pkg/tfbridge/info.go:730 +0x1d9
    github.com/pulumi/pulumi-aiven/provider/v3.Provider(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/pulumi-aiven/pulumi-aiven/provider/resources.go:256 +0x45ea
    main.main()
        /home/runner/work/pulumi-aiven/pulumi-aiven/provider/cmd/pulumi-resource-aiven/main.go:27 +0x37
 
  pulumi:providers:aiven (main):
    error: could not read plugin [/Users/clstokes/.pulumi/plugins/resource-aiven-v3.4.3/pulumi-resource-aiven] stdout: EOF

```

#### Code to reproduce

```ts
import * as aiven from "@pulumi/aiven";

const aProvider = new aiven.Provider("main",{
    apiToken: "asdf",
});
```

## Steps to reproduce

1. `pulumi new typescript -y`
2. overwrite the `index.ts` with the code above
3. `npm i @pulumi/aiven`
4. `pulumi pre`
    - **observe preview fails**
3. `npm i @pulumi/aiven@3.3.4`
4. `pulumi pre`
    - **observe preview completes successfully**

## Context (Environment)

```
% pulumi version
v2.20.0
```

**Comment by alexhwoods** [comment]
We're also experiencing this

**Comment by stack72** [comment]
Hi @clstokes / @alexhwoods

My apologies for this - pr on it's way to fix and will cut a release immediately!
